/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myfirstjavaapp;
import com.Calculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
  
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
Calculator obj=new Calculator();
System.out.println(obj.add(10,5));
    }
}
